# Generated by Django 5.2.11 on 2026-03-05 11:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePipeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Pipeline Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, help_text='If true, new cases without explicit pipeline go here')),
                ('is_active', models.BooleanField(default=True)),
                ('sla_priority_multipliers', models.JSONField(blank=True, default=dict, help_text='SLA multipliers by priority, e.g. {"urgent": 0.5, "high": 0.75, "medium": 1.0, "low": 1.5}')),
                ('auto_escalate', models.BooleanField(default=False, help_text='Auto-escalate cases when SLA is breached')),
            ],
            options={
                'verbose_name': 'Case Pipeline',
                'verbose_name_plural': 'Case Pipelines',
                'db_table': 'case_pipeline',
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CaseStage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Stage Name')),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('stage_type', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('maps_to_status', models.CharField(blank=True, choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Pending', 'Pending'), ('Closed', 'Closed'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate')], help_text='When case enters this stage, also update Case.status', max_length=64, null=True, verbose_name='Maps to Status')),
                ('wip_limit', models.PositiveIntegerField(blank=True, help_text='Maximum cases allowed in this stage (null = unlimited)', null=True, verbose_name='WIP Limit')),
            ],
            options={
                'verbose_name': 'Case Stage',
                'verbose_name_plural': 'Case Stages',
                'db_table': 'case_stage',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'db_table': 'solution',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('status', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Pending', 'Pending'), ('Closed', 'Closed'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate')], max_length=64)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=64)),
                ('case_type', models.CharField(blank=True, choices=[('Question', 'Question'), ('Incident', 'Incident'), ('Problem', 'Problem')], default=None, max_length=255, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='First Response At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('sla_first_response_hours', models.PositiveIntegerField(default=4, help_text='Target hours for first response', verbose_name='First Response SLA (hours)')),
                ('sla_resolution_hours', models.PositiveIntegerField(default=24, help_text='Target hours for resolution', verbose_name='Resolution SLA (hours)')),
                ('kanban_order', models.DecimalField(decimal_places=6, default=0, help_text='Order within the kanban column for drag-drop positioning', max_digits=15, verbose_name='Kanban Order')),
                ('omni_ticket_item_id', models.CharField(blank=True, db_index=True, help_text='TalkHub Omni ticket item ID', max_length=255, null=True)),
                ('omni_ticket_list_id', models.CharField(blank=True, help_text='TalkHub Omni ticket list ID', max_length=255, null=True)),
                ('sla_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='SLA priority level — affects response/resolution targets', max_length=20)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0, help_text='Current escalation level (0=none, 1=L1, 2=L2, 3=L3)')),
                ('escalated_at', models.DateTimeField(blank=True, help_text='When the case was last escalated', null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_cases', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'case',
                'ordering': ('-created_at',),
            },
        ),
    ]
