# Generated by Django 5.2.11 on 2026-03-05 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('common', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ManyToManyField(related_name='case_assigned_users', to='common.profile'),
        ),
        migrations.AddField(
            model_name='case',
            name='contacts',
            field=models.ManyToManyField(related_name='case_contacts', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='case',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='common.org'),
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='case_tags', to='common.tags'),
        ),
        migrations.AddField(
            model_name='case',
            name='teams',
            field=models.ManyToManyField(related_name='cases_teams', to='common.teams'),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='casepipeline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='casepipeline',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_pipelines', to='common.org'),
        ),
        migrations.AddField(
            model_name='casepipeline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='casestage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='casestage',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_stages', to='common.org'),
        ),
        migrations.AddField(
            model_name='casestage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='cases.casepipeline'),
        ),
        migrations.AddField(
            model_name='casestage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='case',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Current pipeline stage (null = use status-based kanban)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.casestage'),
        ),
        migrations.AddField(
            model_name='solution',
            name='cases',
            field=models.ManyToManyField(blank=True, related_name='solutions', to='cases.case'),
        ),
        migrations.AddField(
            model_name='solution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='solution',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='common.org'),
        ),
        migrations.AddField(
            model_name='solution',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddIndex(
            model_name='casepipeline',
            index=models.Index(fields=['org', '-created_at'], name='case_pipeli_org_id_f4590e_idx'),
        ),
        migrations.AddConstraint(
            model_name='casepipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('org',), name='unique_default_case_pipeline_per_org'),
        ),
        migrations.AddIndex(
            model_name='casestage',
            index=models.Index(fields=['org', 'order'], name='case_stage_org_id_b9d581_idx'),
        ),
        migrations.AddIndex(
            model_name='casestage',
            index=models.Index(fields=['pipeline', 'order'], name='case_stage_pipelin_3fbf31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casestage',
            unique_together={('pipeline', 'name')},
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='case_status_deb121_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='case_priorit_bccbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['org', '-created_at'], name='case_org_id_9c4eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['stage', 'kanban_order'], name='case_stage_i_f04bec_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'kanban_order'], name='case_status_a33019_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['status'], name='solution_status_c9b160_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['is_published'], name='solution_is_publ_2f7331_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['org'], name='solution_org_id_577c5c_idx'),
        ),
    ]
