# Generated by Django 5.2.11 on 2026-03-05 11:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('common', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numero', models.PositiveIntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=8, help_text='Valor na moeda original', max_digits=18)),
                ('valor_parcela_convertido', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(choices=[('USD', 'USD - Dólar Americano'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - Libra Esterlina'), ('INR', 'INR - Rupia Indiana'), ('CAD', 'CAD - Dólar Canadense'), ('AUD', 'AUD - Dólar Australiano'), ('JPY', 'JPY - Iene'), ('CNY', 'CNY - Yuan'), ('CHF', 'CHF - Franco Suíço'), ('SGD', 'SGD - Dólar de Singapura'), ('AED', 'AED - Dirham'), ('BRL', 'BRL - Real'), ('MXN', 'MXN - Peso Mexicano'), ('BTC', 'BTC - Bitcoin'), ('ETH', 'ETH - Ethereum'), ('USDT', 'USDT - Tether'), ('USDC', 'USDC - USD Coin'), ('SOL', 'SOL - Solana'), ('BNB', 'BNB - Binance Coin'), ('XRP', 'XRP - Ripple'), ('ADA', 'ADA - Cardano')], max_length=5)),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=10)),
                ('competencia_ano', models.IntegerField(blank=True, null=True)),
                ('competencia_mes', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'db_table': 'financeiro_parcela',
                'ordering': ['lancamento', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('pix_qrcode', 'PIX QR Code'), ('pix_manual', 'PIX Manual'), ('gateway', 'Gateway de Pagamento')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('failed', 'Falhou'), ('expired', 'Expirado'), ('refunded', 'Estornado')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='BRL', max_length=5)),
                ('pix_txid', models.CharField(blank=True, help_text='Identificador único da transação PIX', max_length=255, null=True)),
                ('pix_e2e_id', models.CharField(blank=True, help_text='End-to-end ID do PIX (preenchido na confirmação)', max_length=255, null=True)),
                ('gateway_reference', models.CharField(blank=True, help_text='Referência do gateway de pagamento', max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('_payer_document', models.CharField(blank=True, db_column='payer_document', help_text='CPF/CNPJ criptografado com Fernet', max_length=500, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanoDeContas',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Planos de Contas',
                'db_table': 'financeiro_plano_contas',
                'ordering': ['grupo__ordem', 'grupo__codigo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoDeContasGrupo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo', models.CharField(help_text='Código do grupo (ex: 1.1, 2.1)', max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Grupo do Plano de Contas',
                'verbose_name_plural': 'Grupos do Plano de Contas',
                'db_table': 'financeiro_plano_grupo',
                'ordering': ['ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'db_table': 'financeiro_forma_pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('PAGAR', 'Conta a Pagar'), ('RECEBER', 'Conta a Receber')], max_length=10)),
                ('descricao', models.CharField(max_length=500)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('currency', models.CharField(choices=[('USD', 'USD - Dólar Americano'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - Libra Esterlina'), ('INR', 'INR - Rupia Indiana'), ('CAD', 'CAD - Dólar Canadense'), ('AUD', 'AUD - Dólar Australiano'), ('JPY', 'JPY - Iene'), ('CNY', 'CNY - Yuan'), ('CHF', 'CHF - Franco Suíço'), ('SGD', 'SGD - Dólar de Singapura'), ('AED', 'AED - Dirham'), ('BRL', 'BRL - Real'), ('MXN', 'MXN - Peso Mexicano'), ('BTC', 'BTC - Bitcoin'), ('ETH', 'ETH - Ethereum'), ('USDT', 'USDT - Tether'), ('USDC', 'USDC - USD Coin'), ('SOL', 'SOL - Solana'), ('BNB', 'BNB - Binance Coin'), ('XRP', 'XRP - Ripple'), ('ADA', 'ADA - Cardano')], default='BRL', max_length=5)),
                ('valor_total', models.DecimalField(decimal_places=8, help_text='Valor na moeda original', max_digits=18)),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=8, default=Decimal('1'), help_text='1 unidade da moeda = X unidades da moeda base da org', max_digits=18)),
                ('valor_convertido', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor convertido para moeda base da org (auto-calculado)', max_digits=18)),
                ('numero_parcelas', models.PositiveIntegerField(default=1)),
                ('data_primeiro_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=10)),
                ('competencia_ano', models.IntegerField(blank=True, null=True)),
                ('competencia_mes', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.formapagamento')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'db_table': 'financeiro_lancamento',
                'ordering': ['-data_primeiro_vencimento', '-created_at'],
            },
        ),
    ]
