# Generated by Django 5.2.11 on 2026-03-05 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('contacts', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('invoices', '0001_initial'),
        ('opportunity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='org',
            field=models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.lancamento'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='org',
            field=models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pix_transactions', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pix_transactions', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='lancamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pix_transactions', to='financeiro.lancamento'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='org',
            field=models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='planodecontas',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='planodecontas',
            name='org',
            field=models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org'),
        ),
        migrations.AddField(
            model_name='planodecontas',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='plano_de_contas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.planodecontas'),
        ),
        migrations.AddField(
            model_name='planodecontasgrupo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='planodecontasgrupo',
            name='org',
            field=models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org'),
        ),
        migrations.AddField(
            model_name='planodecontasgrupo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='planodecontas',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='financeiro.planodecontasgrupo'),
        ),
        migrations.AlterUniqueTogether(
            name='formapagamento',
            unique_together={('nome', 'org')},
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['org', 'status'], name='financeiro__org_id_d90510_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['org', 'data_vencimento'], name='financeiro__org_id_b038ab_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['org', 'status', 'data_vencimento'], name='financeiro__org_id_730a38_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['org', 'competencia_ano', 'competencia_mes'], name='financeiro__org_id_0747b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parcela',
            unique_together={('lancamento', 'numero')},
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['org', '-created_at'], name='payment_tra_org_id_0ff05c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['org', 'status'], name='payment_tra_org_id_0af6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['org', 'transaction_type'], name='payment_tra_org_id_245dad_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['pix_txid'], name='payment_tra_pix_txi_b5a91d_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('pix_txid__isnull', False)), fields=('org', 'pix_txid'), name='payment_transaction_pix_txid_unique_per_org'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['org', 'tipo'], name='financeiro__org_id_4fb16a_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['org', 'status'], name='financeiro__org_id_1379cb_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['org', 'tipo', 'status'], name='financeiro__org_id_4e3fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['org', 'competencia_ano', 'competencia_mes'], name='financeiro__org_id_231170_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['account'], name='financeiro__account_088532_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['contact'], name='financeiro__contact_d0eb20_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['plano_de_contas'], name='financeiro__plano_d_f37988_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['data_primeiro_vencimento'], name='financeiro__data_pr_5f7c9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planodecontasgrupo',
            unique_together={('codigo', 'org')},
        ),
        migrations.AlterUniqueTogether(
            name='planodecontas',
            unique_together={('grupo', 'nome', 'org')},
        ),
    ]
