# Generated by Django 5.2.11 on 2026-03-05 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('cases', '0002_initial'),
        ('common', '0001_initial'),
        ('contacts', '0001_initial'),
        ('leads', '0001_initial'),
        ('opportunity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('talkhub_list_id', models.CharField(blank=True, help_text='TalkHub Omni ticket list ID', max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='common.org')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'db_table': 'board',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('limit', models.PositiveIntegerField(blank=True, null=True)),
                ('talkhub_stage_id', models.CharField(blank=True, help_text='TalkHub ticket list stage/status ID', max_length=100, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tasks.board')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_columns', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Board Column',
                'verbose_name_plural': 'Board Columns',
                'db_table': 'board_column',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tasks.board')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='common.org')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Board Member',
                'verbose_name_plural': 'Board Members',
                'db_table': 'board_member',
            },
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='boards', through='tasks.BoardMember', to='common.profile'),
        ),
        migrations.CreateModel(
            name='BoardTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('talkhub_item_id', models.CharField(blank=True, help_text='TalkHub Omni ticket item ID', max_length=100, null=True)),
                ('talkhub_custom_data', models.JSONField(blank=True, default=dict, help_text='TalkHub ticket custom fields (text1-5, select1-5, etc.)')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_tasks', to='accounts.account')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_board_tasks', to='common.profile')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.boardcolumn')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_tasks', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_tasks', to='opportunity.opportunity')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_tasks', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Board Task',
                'verbose_name_plural': 'Board Tasks',
                'db_table': 'board_task',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TaskPipeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Pipeline Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, help_text='If true, new tasks without explicit pipeline go here')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_pipelines', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Task Pipeline',
                'verbose_name_plural': 'Task Pipelines',
                'db_table': 'task_pipeline',
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Stage Name')),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('stage_type', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=20)),
                ('maps_to_status', models.CharField(blank=True, help_text='When task enters this stage, also update Task.status', max_length=50, null=True, verbose_name='Maps to Status')),
                ('wip_limit', models.PositiveIntegerField(blank=True, help_text='Maximum tasks allowed in this stage (null = unlimited)', null=True, verbose_name='WIP Limit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_stages', to='common.org')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tasks.taskpipeline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Task Stage',
                'verbose_name_plural': 'Task Stages',
                'db_table': 'task_stage',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50, verbose_name='status')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50, verbose_name='priority')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('kanban_order', models.DecimalField(decimal_places=6, default=0, help_text='Order within the kanban column for drag-drop positioning', max_digits=15, verbose_name='Kanban Order')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_tasks', to='accounts.account')),
                ('assigned_to', models.ManyToManyField(related_name='task_assigned_users', to='common.profile')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_tasks', to='cases.case')),
                ('contacts', models.ManyToManyField(related_name='task_contacts', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks', to='leads.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_tasks', to='opportunity.opportunity')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='common.org')),
                ('tags', models.ManyToManyField(blank=True, related_name='task_tags', to='common.tags')),
                ('teams', models.ManyToManyField(related_name='tasks_teams', to='common.teams')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('stage', models.ForeignKey(blank=True, help_text='Custom pipeline stage (if using pipeline mode)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskstage')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'task',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='boardcolumn',
            index=models.Index(fields=['org', 'order'], name='board_colum_org_id_c9ff44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boardcolumn',
            unique_together={('board', 'name')},
        ),
        migrations.AddIndex(
            model_name='boardmember',
            index=models.Index(fields=['org', '-created_at'], name='board_membe_org_id_16f9e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boardmember',
            unique_together={('board', 'profile')},
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['org', '-created_at'], name='board_org_id_07a8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='boardtask',
            index=models.Index(fields=['org', 'order'], name='board_task_org_id_6055e2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskpipeline',
            index=models.Index(fields=['org', '-created_at'], name='task_pipeli_org_id_5f31c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskpipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('org',), name='unique_default_task_pipeline_per_org'),
        ),
        migrations.AddIndex(
            model_name='taskstage',
            index=models.Index(fields=['org', 'order'], name='task_stage_org_id_cfad78_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstage',
            index=models.Index(fields=['pipeline', 'order'], name='task_stage_pipelin_f4ed15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskstage',
            unique_together={('pipeline', 'name')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_status_e9a322_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='task_due_dat_6ddd76_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['org', '-created_at'], name='task_org_id_74b184_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'kanban_order'], name='task_status_e6f973_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['stage', 'kanban_order'], name='task_stage_i_a7a1b0_idx'),
        ),
    ]
