# Generated by Django 5.2.11 on 2026-03-05 11:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('common', '0001_initial'),
        ('contacts', '0001_initial'),
        ('invoices', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Opportunity Name')),
                ('stage', models.CharField(choices=[('PROSPECTING', 'Prospecting'), ('QUALIFICATION', 'Qualification'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], default='PROSPECTING', max_length=64, verbose_name='Stage')),
                ('opportunity_type', models.CharField(blank=True, choices=[('NEW_BUSINESS', 'New Business'), ('EXISTING_BUSINESS', 'Existing Business'), ('RENEWAL', 'Renewal'), ('UPSELL', 'Upsell'), ('CROSS_SELL', 'Cross-sell')], max_length=64, null=True, verbose_name='Type')),
                ('currency', models.CharField(blank=True, choices=[('BRL', 'BRL, Real'), ('USD', 'USD, Dollar'), ('EUR', 'EUR, Euro'), ('GBP', 'GBP, Pound'), ('INR', 'INR, Rupee'), ('CAD', 'CAD, Dollar'), ('AUD', 'AUD, Dollar'), ('JPY', 'JPY, Yen'), ('CNY', 'CNY, Yuan'), ('CHF', 'CHF, Franc'), ('SGD', 'SGD, Dollar'), ('AED', 'AED, Dirham'), ('MXN', 'MXN, Peso'), ('BTC', 'BTC, Bitcoin'), ('ETH', 'ETH, Ethereum'), ('USDT', 'USDT, Tether'), ('USDC', 'USDC, USD Coin'), ('SOL', 'SOL, Solana'), ('BNB', 'BNB, Binance Coin'), ('XRP', 'XRP, Ripple'), ('ADA', 'ADA, Cardano')], max_length=10, null=True, verbose_name='Currency')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount')),
                ('amount_source', models.CharField(choices=[('MANUAL', 'Manual'), ('CALCULATED', 'Calculated from Products')], default='MANUAL', max_length=20, verbose_name='Amount Source')),
                ('probability', models.IntegerField(blank=True, default=0, null=True, verbose_name='Probability (%)')),
                ('closed_on', models.DateField(blank=True, null=True, verbose_name='Expected Close Date')),
                ('lead_source', models.CharField(blank=True, choices=[('NONE', 'NONE'), ('CALL', 'CALL'), ('EMAIL', ' EMAIL'), ('EXISTING CUSTOMER', 'EXISTING CUSTOMER'), ('PARTNER', 'PARTNER'), ('PUBLIC RELATIONS', 'PUBLIC RELATIONS'), ('CAMPAIGN', 'CAMPAIGN'), ('WEBSITE', 'WEBSITE'), ('OTHER', 'OTHER')], max_length=255, null=True, verbose_name='Lead Source')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('stage_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Stage Changed At')),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='accounts.account')),
                ('assigned_to', models.ManyToManyField(related_name='opportunity_assigned_users', to='common.profile')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_closed_by', to='common.profile')),
                ('contacts', models.ManyToManyField(related_name='opportunity_contacts', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead', models.ForeignKey(blank=True, help_text='Lead that originated this opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='leads.lead')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='common.org')),
                ('tags', models.ManyToManyField(blank=True, related_name='opportunity_tags', to='common.tags')),
                ('teams', models.ManyToManyField(related_name='opportunity_teams', to='common.teams')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'db_table': 'opportunity',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OpportunityLineItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Item Name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unit Price')),
                ('discount_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount')], max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Value')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='opportunity.opportunity')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_line_items', to='common.org')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_line_items', to='invoices.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Opportunity Line Item',
                'verbose_name_plural': 'Opportunity Line Items',
                'db_table': 'opportunity_line_item',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesGoal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Goal Name')),
                ('goal_type', models.CharField(choices=[('REVENUE', 'Revenue'), ('DEALS_CLOSED', 'Deals Closed')], max_length=20, verbose_name='Goal Type')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Target Value')),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], max_length=20, verbose_name='Period Type')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('is_active', models.BooleanField(default=True)),
                ('milestone_50_notified', models.BooleanField(default=False)),
                ('milestone_90_notified', models.BooleanField(default=False)),
                ('milestone_100_notified', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_goals', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_goals', to='common.org')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_goals', to='common.teams')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Sales Goal',
                'verbose_name_plural': 'Sales Goals',
                'db_table': 'sales_goal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalBreakdown',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('breakdown_type', models.CharField(choices=[('user', 'Por Usuário'), ('product', 'Por Produto'), ('channel', 'Por Canal'), ('stage', 'Por Estágio')], max_length=20, verbose_name='Tipo de Desdobramento')),
                ('breakdown_key', models.CharField(help_text='ID do usuário, produto, canal ou estágio', max_length=255, verbose_name='Chave')),
                ('breakdown_label', models.CharField(help_text='Nome legível (ex: nome do usuário, nome do produto)', max_length=255, verbose_name='Rótulo')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta Parcial')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valor Atual')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_breakdowns', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='opportunity.salesgoal')),
            ],
            options={
                'verbose_name': 'Goal Breakdown',
                'verbose_name_plural': 'Goal Breakdowns',
                'db_table': 'goal_breakdown',
                'ordering': ['breakdown_type', 'breakdown_label'],
            },
        ),
        migrations.CreateModel(
            name='StageAgingConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage', models.CharField(choices=[('PROSPECTING', 'Prospecting'), ('QUALIFICATION', 'Qualification'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], max_length=64, verbose_name='Stage')),
                ('expected_days', models.PositiveIntegerField(default=14, verbose_name='Expected Days')),
                ('warning_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Warning Days')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_aging_configs', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Stage Aging Config',
                'verbose_name_plural': 'Stage Aging Configs',
                'db_table': 'stage_aging_config',
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage'], name='opportunity_stage_39fb59_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['org', '-created_at'], name='opportunity_org_id_945a7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('probability__gte', 0), ('probability__lte', 100)), name='opportunity_probability_range'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('amount__isnull', True), _connector='OR'), name='opportunity_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='opportunitylineitem',
            index=models.Index(fields=['opportunity'], name='opportunity_opportu_456e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitylineitem',
            index=models.Index(fields=['org'], name='opportunity_org_id_c76c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesgoal',
            index=models.Index(fields=['org', '-created_at'], name='sales_goal_org_id_363225_idx'),
        ),
        migrations.AddIndex(
            model_name='salesgoal',
            index=models.Index(fields=['org', 'period_start', 'period_end'], name='sales_goal_org_id_f5e0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='goalbreakdown',
            index=models.Index(fields=['org', '-created_at'], name='goal_breakd_org_id_f9c096_idx'),
        ),
        migrations.AddIndex(
            model_name='goalbreakdown',
            index=models.Index(fields=['goal', 'breakdown_type'], name='goal_breakd_goal_id_ec9afd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goalbreakdown',
            unique_together={('goal', 'breakdown_type', 'breakdown_key')},
        ),
        migrations.AlterUniqueTogether(
            name='stageagingconfig',
            unique_together={('org', 'stage')},
        ),
    ]
