# Generated by Django 5.2.11 on 2026-03-05 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('channel_type', models.CharField(choices=[('talkhub_omni', 'TalkHub Omni'), ('smtp_native', 'SMTP Nativo'), ('chatwoot', 'Chatwoot'), ('evolution_api', 'Evolution API'), ('whatsapp_direct', 'WhatsApp Direto'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('email', 'Email'), ('webchat', 'Web Chat')], max_length=50)),
                ('provider', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('capabilities_json', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'channel_config',
            },
        ),
    ]
