# Generated by Django 5.2.11 on 2026-03-05 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channelconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='channelconfig',
            name='org',
            field=models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org'),
        ),
        migrations.AddField(
            model_name='channelconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddIndex(
            model_name='channelconfig',
            index=models.Index(fields=['org', 'channel_type'], name='channel_con_org_id_7c88c8_idx'),
        ),
        migrations.AddIndex(
            model_name='channelconfig',
            index=models.Index(fields=['org', 'is_active'], name='channel_con_org_id_539241_idx'),
        ),
    ]
