# Generated by Django 5.2.11 on 2026-03-05 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('channel', models.CharField(max_length=50)),
                ('integration_provider', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('pending', 'Pendente'), ('resolved', 'Concluída')], default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('omni_user_ns', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to='common.profile')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('tags', models.ManyToManyField(blank=True, related_name='conversation_tags', to='common.tags')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'conversation',
                'ordering': ('-last_message_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('direction', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída'), ('agent', 'Agente'), ('note', 'Nota'), ('system', 'Sistema')], max_length=10)),
                ('msg_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('file', 'Arquivo'), ('payload', 'Payload Estruturado')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('media_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('sender_type', models.CharField(blank=True, default='', max_length=50)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_id', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'message',
                'ordering': ('timestamp',),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['org', '-last_message_at'], name='conversatio_org_id_05f083_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['org', 'status'], name='conversatio_org_id_a3a53d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['org', 'channel'], name='conversatio_org_id_b21cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['contact'], name='conversatio_contact_01bba7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['omni_user_ns'], name='conversatio_omni_us_3993ea_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='message_convers_200936_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['org', '-timestamp'], name='message_org_id_fbe7f2_idx'),
        ),
    ]
