# Generated by Django 5.2.11 on 2026-03-05 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('automation_type', models.CharField(choices=[('routine', 'Routine'), ('logic_rule', 'Logic Rule'), ('social', 'Social')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'automation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped')], max_length=20)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'automation_log',
                'ordering': ('-created_at',),
            },
        ),
    ]
