# Generated by Django 5.2.11 on 2026-03-05 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='automation',
            name='org',
            field=models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org'),
        ),
        migrations.AddField(
            model_name='automation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='automationlog',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automations.automation'),
        ),
        migrations.AddField(
            model_name='automationlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='automationlog',
            name='org',
            field=models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org'),
        ),
        migrations.AddField(
            model_name='automationlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['org', '-created_at'], name='automation_org_id_83152a_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['automation_type', 'is_active'], name='automation_automat_4176ab_idx'),
        ),
        migrations.AddIndex(
            model_name='automationlog',
            index=models.Index(fields=['org', '-created_at'], name='automation__org_id_14b469_idx'),
        ),
        migrations.AddIndex(
            model_name='automationlog',
            index=models.Index(fields=['automation', '-created_at'], name='automation__automat_cf553f_idx'),
        ),
        migrations.AddIndex(
            model_name='automationlog',
            index=models.Index(fields=['status'], name='automation__status_43c42a_idx'),
        ),
    ]
