# Generated by Django 5.2.11 on 2026-03-05 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('connector_slug', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('crm_value', models.JSONField()),
                ('external_value', models.JSONField()),
                ('resolved_by', models.CharField(choices=[('crm', 'CRM'), ('external', 'External'), ('last_write', 'Last Write')], max_length=20)),
                ('fields_overwritten', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'conflict_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['org', '-created_at'], name='conflict_lo_org_id_6eacd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('connector_slug', models.CharField(max_length=100)),
                ('source_field', models.CharField(max_length=255)),
                ('target_field', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('concat', 'Concatenation'), ('split', 'Split'), ('phone_format', 'Phone Format')], default='text', max_length=20)),
                ('transform_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'field_mapping',
                'indexes': [models.Index(fields=['org', 'connector_slug'], name='field_mappi_org_id_1e5b5b_idx')],
                'unique_together': {('org', 'connector_slug', 'source_field')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('connector_slug', models.CharField(db_index=True, max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60, help_text='Intervalo de sincronização em minutos (5-1440)')),
                ('conflict_strategy', models.CharField(choices=[('last_write_wins', 'Last Write Wins'), ('crm_wins', 'CRM Wins'), ('external_wins', 'External Wins')], default='last_write_wins', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'integration_connection',
                'indexes': [models.Index(fields=['org', 'connector_slug'], name='integration_org_id_cf147c_idx'), models.Index(fields=['is_active'], name='integration_is_acti_d756b7_idx')],
                'unique_together': {('org', 'connector_slug')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('connector_slug', models.CharField(db_index=True, max_length=100)),
                ('operation', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=10)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'integration_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['org', '-created_at'], name='integration_org_id_67f01b_idx'), models.Index(fields=['connector_slug', 'status'], name='integration_connect_52b686_idx'), models.Index(fields=['entity_type', 'entity_id'], name='integration_entity__304bce_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrgFeatureFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('feature_key', models.CharField(db_index=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'org_feature_flag',
                'indexes': [models.Index(fields=['org', 'feature_key'], name='org_feature_org_id_82b3c5_idx')],
                'unique_together': {('org', 'feature_key')},
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('connector_slug', models.CharField(db_index=True, max_length=100)),
                ('sync_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('progress_detail', models.JSONField(blank=True, default=dict)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'sync_job',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['org', '-created_at'], name='sync_job_org_id_65c4e6_idx'), models.Index(fields=['connector_slug', 'status'], name='sync_job_connect_60aa1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('connector_slug', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processed', 'Processed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='queued', max_length=20)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'webhook_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['org', '-created_at'], name='webhook_log_org_id_0dcedf_idx'), models.Index(fields=['connector_slug', 'event_type'], name='webhook_log_connect_039838_idx')],
            },
        ),
    ]
