/**
 * Opções de campos de lead correspondendo ao backend Django
 * @module lib/constants/lead-choices
 */

/** @type {{ value: string, label: string }[]} */
export const INDUSTRIES = [
  { value: '', label: 'Selecionar Setor' },
  { value: 'ADVERTISING', label: 'Publicidade' },
  { value: 'AGRICULTURE', label: 'Agricultura' },
  { value: 'APPAREL & ACCESSORIES', label: 'Vestuário e Acessórios' },
  { value: 'AUTOMOTIVE', label: 'Automotivo' },
  { value: 'BANKING', label: 'Bancário' },
  { value: 'BIOTECHNOLOGY', label: 'Biotecnologia' },
  { value: 'BUILDING MATERIALS & EQUIPMENT', label: 'Materiais e Equipamentos de Construção' },
  { value: 'CHEMICAL', label: 'Químico' },
  { value: 'COMPUTER', label: 'Informática' },
  { value: 'EDUCATION', label: 'Educação' },
  { value: 'ELECTRONICS', label: 'Eletrônicos' },
  { value: 'ENERGY', label: 'Energia' },
  { value: 'ENTERTAINMENT & LEISURE', label: 'Entretenimento e Lazer' },
  { value: 'FINANCE', label: 'Finanças' },
  { value: 'FOOD & BEVERAGE', label: 'Alimentos e Bebidas' },
  { value: 'GROCERY', label: 'Varejo Alimentar' },
  { value: 'HEALTHCARE', label: 'Saúde' },
  { value: 'INSURANCE', label: 'Seguros' },
  { value: 'LEGAL', label: 'Jurídico' },
  { value: 'MANUFACTURING', label: 'Manufatura' },
  { value: 'PUBLISHING', label: 'Editorial' },
  { value: 'REAL ESTATE', label: 'Imobiliário' },
  { value: 'SERVICE', label: 'Serviços' },
  { value: 'SOFTWARE', label: 'Software' },
  { value: 'SPORTS', label: 'Esportes' },
  { value: 'TECHNOLOGY', label: 'Tecnologia' },
  { value: 'TELECOMMUNICATIONS', label: 'Telecomunicações' },
  { value: 'TELEVISION', label: 'Televisão' },
  { value: 'TRANSPORTATION', label: 'Transporte' },
  { value: 'VENTURE CAPITAL', label: 'Capital de Risco' }
];

/** @type {{ value: string, label: string }[]} */
export const COUNTRIES = [
  { value: '', label: 'Selecionar País' },
  { value: 'BR', label: 'Brasil' },
  { value: 'US', label: 'Estados Unidos' },
  { value: 'PT', label: 'Portugal' },
  { value: 'AR', label: 'Argentina' },
  { value: 'MX', label: 'México' },
  { value: 'CO', label: 'Colômbia' },
  { value: 'CL', label: 'Chile' },
  { value: 'PE', label: 'Peru' },
  { value: 'UY', label: 'Uruguai' },
  { value: 'DE', label: 'Alemanha' },
  { value: 'FR', label: 'França' },
  { value: 'GB', label: 'Reino Unido' },
  { value: 'ES', label: 'Espanha' },
  { value: 'IT', label: 'Itália' },
  { value: 'CA', label: 'Canadá' },
  { value: 'AU', label: 'Austrália' },
  { value: 'IN', label: 'Índia' },
  { value: 'CN', label: 'China' },
  { value: 'JP', label: 'Japão' },
  { value: 'NL', label: 'Países Baixos' },
  { value: 'SE', label: 'Suécia' },
  { value: 'CH', label: 'Suíça' },
  { value: 'SG', label: 'Singapura' },
  { value: 'AE', label: 'Emirados Árabes' },
  { value: 'AF', label: 'Afeganistão' },
  { value: 'AL', label: 'Albânia' },
  { value: 'DZ', label: 'Argélia' },
  { value: 'AM', label: 'Armênia' },
  { value: 'AT', label: 'Áustria' },
  { value: 'AZ', label: 'Azerbaijão' },
  { value: 'BH', label: 'Bahrein' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BY', label: 'Bielorrússia' },
  { value: 'BE', label: 'Bélgica' },
  { value: 'BG', label: 'Bulgária' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'HR', label: 'Croácia' },
  { value: 'CY', label: 'Chipre' },
  { value: 'CZ', label: 'República Tcheca' },
  { value: 'DK', label: 'Dinamarca' },
  { value: 'EG', label: 'Egito' },
  { value: 'EE', label: 'Estônia' },
  { value: 'FI', label: 'Finlândia' },
  { value: 'GE', label: 'Geórgia' },
  { value: 'GR', label: 'Grécia' },
  { value: 'HK', label: 'Hong Kong' },
  { value: 'HU', label: 'Hungria' },
  { value: 'IS', label: 'Islândia' },
  { value: 'ID', label: 'Indonésia' },
  { value: 'IR', label: 'Irã' },
  { value: 'IQ', label: 'Iraque' },
  { value: 'IE', label: 'Irlanda' },
  { value: 'IL', label: 'Israel' },
  { value: 'JO', label: 'Jordânia' },
  { value: 'KZ', label: 'Cazaquistão' },
  { value: 'KE', label: 'Quênia' },
  { value: 'KW', label: 'Kuwait' },
  { value: 'LV', label: 'Letônia' },
  { value: 'LB', label: 'Líbano' },
  { value: 'LT', label: 'Lituânia' },
  { value: 'LU', label: 'Luxemburgo' },
  { value: 'MY', label: 'Malásia' },
  { value: 'MT', label: 'Malta' },
  { value: 'MA', label: 'Marrocos' },
  { value: 'NZ', label: 'Nova Zelândia' },
  { value: 'NG', label: 'Nigéria' },
  { value: 'NO', label: 'Noruega' },
  { value: 'OM', label: 'Omã' },
  { value: 'PK', label: 'Paquistão' },
  { value: 'PH', label: 'Filipinas' },
  { value: 'PL', label: 'Polônia' },
  { value: 'QA', label: 'Catar' },
  { value: 'RO', label: 'Romênia' },
  { value: 'RU', label: 'Rússia' },
  { value: 'SA', label: 'Arábia Saudita' },
  { value: 'RS', label: 'Sérvia' },
  { value: 'SK', label: 'Eslováquia' },
  { value: 'SI', label: 'Eslovênia' },
  { value: 'ZA', label: 'África do Sul' },
  { value: 'KR', label: 'Coreia do Sul' },
  { value: 'LK', label: 'Sri Lanka' },
  { value: 'TW', label: 'Taiwan' },
  { value: 'TH', label: 'Tailândia' },
  { value: 'TR', label: 'Turquia' },
  { value: 'UA', label: 'Ucrânia' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'VN', label: 'Vietnã' }
];
