# Generated by Django 5.2.11 on 2026-03-05 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(choices=[('email_blast', 'Email Blast'), ('nurture_sequence', 'Nurture Sequence'), ('whatsapp_broadcast', 'WhatsApp Broadcast')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendada'), ('running', 'Em Execução'), ('paused', 'Pausada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body_template', models.TextField(blank=True, default='')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('bounce_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'campaign',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CampaignAudience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('filter_criteria', models.JSONField(blank=True, default=dict)),
                ('contact_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'campaign_audience',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('delivered', 'Entregue'), ('opened', 'Aberto'), ('clicked', 'Clicado'), ('bounced', 'Bounce'), ('failed', 'Falhou'), ('unsubscribed', 'Descadastrado')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('current_step', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'campaign_recipient',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CampaignStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('step_order', models.PositiveIntegerField()),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body_template', models.TextField(blank=True, default='')),
                ('delay_hours', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'campaign_step',
                'ordering': ('step_order',),
            },
        ),
    ]
