# Generated by Django 5.2.11 on 2026-03-05 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('common', '0001_initial'),
        ('contacts', '0001_initial'),
        ('invoices', '0001_initial'),
        ('opportunity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='common.org'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='teams',
            field=models.ManyToManyField(related_name='estimate_teams', to='common.teams'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.estimate'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_line_items', to='common.org'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(blank=True, help_text='The legal entity responsible for payment (REQUIRED via validation)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='assigned_to',
            field=models.ManyToManyField(related_name='invoice_assigned_to', to='common.profile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(blank=True, help_text="The 'Bill To' contact (REQUIRED via validation)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='opportunity',
            field=models.ForeignKey(blank=True, help_text='The sales opportunity this invoice relates to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='common.org'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='teams',
            field=models.ManyToManyField(related_name='invoices_teams', to='common.teams'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='converted_to_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_estimate', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_history', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_histories', to='common.org'),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_history_updated_by', to='common.profile'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_line_items', to='common.org'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='invoicetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='invoicetemplate',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_templates', to='common.org'),
        ),
        migrations.AddField(
            model_name='invoicetemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.invoicetemplate'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.org'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='product',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='common.org'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_line_items', to='invoices.product'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_line_items', to='invoices.product'),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoices', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='assigned_to',
            field=models.ManyToManyField(related_name='recurring_invoice_assigned_to', to='common.profile'),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_invoices', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_invoices', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='common.org'),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='teams',
            field=models.ManyToManyField(related_name='recurring_invoice_teams', to='common.teams'),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='recurringinvoicelineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='recurringinvoicelineitem',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoice_line_items', to='common.org'),
        ),
        migrations.AddField(
            model_name='recurringinvoicelineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_invoice_line_items', to='invoices.product'),
        ),
        migrations.AddField(
            model_name='recurringinvoicelineitem',
            name='recurring_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.recurringinvoice'),
        ),
        migrations.AddField(
            model_name='recurringinvoicelineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['org', '-created_at'], name='estimate_org_id_d4d0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['org', 'status'], name='estimate_org_id_11a35e_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['account'], name='estimate_account_25a4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['expiry_date'], name='estimate_expiry__9e6baa_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['public_token'], name='estimate_public__9ac914_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicehistory',
            index=models.Index(fields=['org', '-created_at'], name='invoice_his_org_id_45400e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicehistory',
            index=models.Index(fields=['invoice'], name='invoice_his_invoice_f9dc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicetemplate',
            index=models.Index(fields=['org', '-created_at'], name='invoice_tem_org_id_e092e5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['org', '-created_at'], name='invoice_org_id_7ae4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['org', 'status'], name='invoice_org_id_a1a9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['account'], name='invoice_account_a00f76_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoice_due_dat_ee8b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['public_token'], name='invoice_public__322f82_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['org', '-payment_date'], name='payment_org_id_9d3110_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='payment_invoice_6a55b6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['org', 'is_active'], name='product_org_id_cfbb38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'org')},
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['org', 'order'], name='invoice_lin_org_id_474821_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatelineitem',
            index=models.Index(fields=['org', 'order'], name='estimate_li_org_id_08f3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoice',
            index=models.Index(fields=['org', '-created_at'], name='recurring_i_org_id_0389ae_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoice',
            index=models.Index(fields=['org', 'is_active'], name='recurring_i_org_id_264608_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoice',
            index=models.Index(fields=['next_generation_date'], name='recurring_i_next_ge_bcc0ef_idx'),
        ),
    ]
