import uuid

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from common.base import BaseOrgModel


class ReminderPolicy(BaseOrgModel):
    """
    Policy that defines when and how reminders are generated for a target entity.

    Supports multiple trigger types (due_date, recurring, cron, event_plus_offset)
    and dispatches via configurable channels with optional task creation.
    """

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, default="")

    # Generic target (ContentType pattern)
    target_content_type = models.ForeignKey(
        ContentType, on_delete=models.CASCADE, related_name="reminder_policies"
    )
    target_object_id = models.UUIDField()
    target = GenericForeignKey("target_content_type", "target_object_id")

    MODULE_KEYS = [
        ("financeiro", "Financeiro"),
        ("leads", "Leads"),
        ("cases", "Cases"),
        ("tasks", "Tasks"),
        ("invoices", "Invoices"),
        ("orders", "Orders"),
        ("opportunity", "Oportunidades"),
    ]
    module_key = models.CharField(max_length=50, choices=MODULE_KEYS)
    owner_user = models.ForeignKey(
        "common.Profile",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="owned_reminder_policies",
    )
    is_active = models.BooleanField(default=True)

    # Trigger configuration
    TRIGGER_TYPES = [
        ("due_date", "Data de vencimento"),
        ("relative_date", "Relativo a data"),
        ("recurring", "Recorrente"),
        ("cron", "Cron expression"),
        ("event_plus_offset", "Evento + offset"),
    ]
    trigger_type = models.CharField(max_length=30, choices=TRIGGER_TYPES)
    trigger_config = models.JSONField(default=dict)
    # Examples:
    # due_date:       {"date_field": "data_vencimento", "offset_days": -3}
    # recurring:      {"interval_days": 3, "max_runs": 10, "start_after": "data_vencimento"}
    # cron:           {"cron_expression": "0 9 * * 1-5"}
    # event_plus_offset: {"event": "parcela.status_changed", "offset_hours": 24}

    # Channel dispatch configuration
    channel_config = models.JSONField(default=dict)
    # Structure: {"channel_type": "smtp_native", "destination_type": "contact_email",
    #   "destination_value": "", "fallback_channel": "internal",
    #   "send_only_business_hours": false, "opt_in_required": false}

    # Task integration configuration
    task_config = models.JSONField(default=dict)
    # Structure: {"enabled": false, "mode": "per_run"|"persistent",
    #   "title_template": "Cobranca: {{contact_name}} - {{invoice_number}}",
    #   "description_template": "...", "assign_to_user_id": null,
    #   "priority": "High", "board_id": null}

    # Message template with {{variable}} interpolation
    message_template = models.TextField(blank=True, default="")

    # Approval policy
    APPROVAL_POLICIES = [
        ("auto", "Auto"),
        ("manual", "Aprovação manual"),
    ]
    approval_policy = models.CharField(
        max_length=20, choices=APPROVAL_POLICIES, default="auto"
    )

    # Scheduling state
    timezone = models.CharField(max_length=50, default="America/Sao_Paulo")
    next_run_at = models.DateTimeField(null=True, blank=True, db_index=True)
    last_run_at = models.DateTimeField(null=True, blank=True)
    run_count = models.PositiveIntegerField(default=0)
    error_count = models.PositiveIntegerField(default=0)

    metadata_json = models.JSONField(default=dict, blank=True)

    class Meta:
        db_table = "assistant_reminder_policy"
        indexes = [
            models.Index(fields=["org", "module_key", "is_active"]),
            models.Index(fields=["org", "next_run_at"]),
            models.Index(
                fields=["target_content_type", "target_object_id"],
                name="idx_reminder_policy_target",
            ),
        ]
        verbose_name = "Reminder Policy"
        verbose_name_plural = "Reminder Policies"

    def __str__(self):
        return f"{self.name} ({self.module_key})"


class ScheduledJob(BaseOrgModel):
    """
    A scheduled unit of work generated by a ReminderPolicy, Automation, or Campaign.

    Jobs are picked up by the executor task (process_scheduled_jobs) every minute.
    Uses SELECT FOR UPDATE SKIP LOCKED to prevent duplicate execution.
    """

    JOB_TYPES = [
        ("reminder", "Lembrete"),
        ("automation", "Automação"),
        ("campaign_step", "Passo de campanha"),
    ]
    job_type = models.CharField(max_length=30, choices=JOB_TYPES)

    # Source (what generated this job — ReminderPolicy, Automation, Campaign)
    source_content_type = models.ForeignKey(
        ContentType, on_delete=models.CASCADE, related_name="+"
    )
    source_object_id = models.UUIDField()
    source = GenericForeignKey("source_content_type", "source_object_id")

    # Target (the entity this job acts upon — Lancamento, Parcela, Lead, etc.)
    target_content_type = models.ForeignKey(
        ContentType, on_delete=models.CASCADE, related_name="+", null=True, blank=True
    )
    target_object_id = models.UUIDField(null=True, blank=True)
    target = GenericForeignKey("target_content_type", "target_object_id")

    assigned_user = models.ForeignKey(
        "common.Profile",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assigned_jobs",
    )
    due_at = models.DateTimeField(db_index=True)

    STATUSES = [
        ("pending", "Pendente"),
        ("locked", "Em execução"),
        ("completed", "Concluído"),
        ("failed", "Falhou"),
        ("cancelled", "Cancelado"),
        ("skipped", "Ignorado"),
    ]
    status = models.CharField(max_length=20, choices=STATUSES, default="pending")

    attempt_count = models.PositiveIntegerField(default=0)
    max_attempts = models.PositiveIntegerField(default=3)
    last_error = models.TextField(blank=True, default="")
    payload = models.JSONField(default=dict)
    idempotency_key = models.CharField(max_length=255, unique=True)

    # Whether this job requires manual approval before execution
    approval_required = models.BooleanField(default=False)

    class Meta:
        db_table = "assistant_scheduled_job"
        indexes = [
            models.Index(fields=["org", "status", "due_at"]),
        ]
        verbose_name = "Scheduled Job"
        verbose_name_plural = "Scheduled Jobs"

    def __str__(self):
        return f"Job {self.job_type} [{self.status}] due={self.due_at}"


class ChannelDispatch(BaseOrgModel):
    """
    Record of a message dispatch attempt through a communication channel.

    Created when a ScheduledJob executes and sends a message.
    Provides unified audit trail across all channels.
    """

    scheduled_job = models.ForeignKey(
        ScheduledJob, on_delete=models.CASCADE, related_name="dispatches"
    )
    channel_type = models.CharField(max_length=50)
    provider_key = models.CharField(max_length=100, blank=True, default="")
    destination = models.CharField(max_length=255)
    message_payload = models.JSONField(default=dict)

    STATUSES = [
        ("pending", "Pendente"),
        ("sent", "Enviado"),
        ("delivered", "Entregue"),
        ("failed", "Falhou"),
        ("bounced", "Bounce"),
    ]
    status = models.CharField(max_length=20, choices=STATUSES, default="pending")

    provider_message_id = models.CharField(max_length=255, blank=True, default="")
    error_message = models.TextField(blank=True, default="")
    sent_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "assistant_channel_dispatch"
        verbose_name = "Channel Dispatch"
        verbose_name_plural = "Channel Dispatches"

    def __str__(self):
        return f"Dispatch {self.channel_type} -> {self.destination} [{self.status}]"


class TaskLink(BaseOrgModel):
    """
    Links an automation source (ReminderPolicy, Automation, Campaign) to a Task.

    Enables bidirectional tracking: from a task you can find what generated it,
    and from an automation you can find all tasks it created.
    """

    # Source (ReminderPolicy, Automation, Campaign)
    source_content_type = models.ForeignKey(
        ContentType, on_delete=models.CASCADE, related_name="+"
    )
    source_object_id = models.UUIDField()
    source = GenericForeignKey("source_content_type", "source_object_id")

    task = models.ForeignKey(
        "tasks.Task", on_delete=models.CASCADE, related_name="automation_links"
    )

    SYNC_MODES = [
        ("persistent", "Persistente"),
        ("per_run", "Por execução"),
    ]
    sync_mode = models.CharField(max_length=20, choices=SYNC_MODES, default="per_run")

    STATUSES = [
        ("active", "Ativo"),
        ("completed", "Concluído"),
        ("cancelled", "Cancelado"),
    ]
    status = models.CharField(max_length=20, choices=STATUSES, default="active")

    class Meta:
        db_table = "assistant_task_link"
        indexes = [
            models.Index(
                fields=["source_content_type", "source_object_id"],
                name="idx_task_link_source",
            ),
            models.Index(fields=["task"]),
        ]
        verbose_name = "Task Link"
        verbose_name_plural = "Task Links"

    def __str__(self):
        return f"TaskLink -> Task {self.task_id} [{self.status}]"


class AssistantSession(BaseOrgModel):
    """Sessão de conversa com o assistente IA."""

    user = models.ForeignKey(
        "common.Profile", on_delete=models.CASCADE, related_name="assistant_sessions"
    )
    title = models.CharField(max_length=200, blank=True, default="")
    context_json = models.JSONField(default=dict, blank=True)
    STATUS_CHOICES = [
        ("active", "Ativa"),
        ("archived", "Arquivada"),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="active")
    last_activity_at = models.DateTimeField(auto_now=True)
    total_tokens = models.PositiveIntegerField(default=0)
    total_cost_usd = models.DecimalField(max_digits=10, decimal_places=6, default=0)

    class Meta:
        db_table = "assistant_session"
        indexes = [
            models.Index(fields=["org", "user", "-last_activity_at"]),
        ]
        verbose_name = "Assistant Session"
        verbose_name_plural = "Assistant Sessions"

    def __str__(self):
        return f"Session {self.title or self.id} ({self.status})"


class AssistantMessage(BaseOrgModel):
    """Mensagem individual na sessão do assistente."""

    session = models.ForeignKey(
        AssistantSession, on_delete=models.CASCADE, related_name="messages"
    )
    ROLE_CHOICES = [
        ("user", "Usuário"),
        ("assistant", "Assistente"),
        ("system", "Sistema"),
        ("tool_call", "Chamada de ferramenta"),
        ("tool_result", "Resultado de ferramenta"),
    ]
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)
    content = models.TextField()
    metadata = models.JSONField(default=dict, blank=True)
    # metadata: {tool_name, tokens_input, tokens_output, cost_usd, latency_ms, model,
    #            proposed_actions, action_results}

    class Meta:
        db_table = "assistant_message"
        ordering = ["created_at"]
        verbose_name = "Assistant Message"
        verbose_name_plural = "Assistant Messages"

    def __str__(self):
        return f"Message [{self.role}] in {self.session_id}"


class AutopilotTemplate(BaseOrgModel):
    """
    Reusable template for quickly creating reminders, rules, or campaigns.

    System templates (is_system=True) are seeded and shared across all orgs.
    Custom templates are org-scoped.
    """

    name = models.CharField(max_length=255)
    CATEGORIES = [
        ("cobranca", "Cobrança"),
        ("follow_up", "Follow-up"),
        ("onboarding", "Onboarding"),
        ("sla", "SLA"),
        ("nurture", "Nutrição"),
        ("operational", "Operacional"),
    ]
    category = models.CharField(max_length=50, choices=CATEGORIES)

    module_key = models.CharField(max_length=50)

    TEMPLATE_TYPES = [
        ("reminder", "Lembrete"),
        ("rule", "Regra"),
        ("campaign", "Campanha"),
    ]
    template_type = models.CharField(max_length=30, choices=TEMPLATE_TYPES)

    config_template = models.JSONField(default=dict)
    message_template = models.TextField(blank=True, default="")
    is_system = models.BooleanField(default=False)

    class Meta:
        db_table = "assistant_autopilot_template"
        verbose_name = "Autopilot Template"
        verbose_name_plural = "Autopilot Templates"

    def __str__(self):
        return f"{self.name} ({self.template_type})"
